apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: cluster-xxx
  # With the current version of configconnector, labels don't get set:
  # https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/110
  #  labels:
  #    builduser: xxx
spec:
  location: us-central1
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  # With the current version of configconnector, releaseChannel doesn't work:
  # https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/109
  #  releaseChannel:
  #    channel: "REGULAR"
