apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: main-nodepool-xxx
  labels:
    builduser: xxx
spec:
  location: us-central1
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 300
  nodeConfig:
    preemptible: false
    serviceAccountRef:
      name: svc-acct-xxx
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: cluster-xxx
