apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: svc-acct-xxx
  labels:
    builduser: xxx
spec:
  displayName: The service account used to run our services
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-logwriter-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/logging.logWriter
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-metricwriter-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/monitoring.metricWriter
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-viewer-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/monitoring.viewer
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-storageadmin-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/storage.objectAdmin
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-cloudtraceagent-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/cloudtrace.agent
  resourceRef:
    kind: Project
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: svc-acct-clouddebuggeragent-xxx
  labels:
    builduser: xxx
spec:
  member: serviceAccount:svc-acct-xxx@<my-project>.iam.gserviceaccount.com
  role: roles/clouddebugger.agent
  resourceRef:
    kind: Project
